pipeline {
    agent none
    stages {
        stage('Build') {
            agent any
            steps {
                echo'build stage..'
                
//                 checkout scm
//                 sh 'make'
//                 stash includes: '**/target/*.jar', name: 'app' 
            }
        }
        stage('Test on Linux') {
            agent { 
                label 'linux'
            }
            steps {
                echo'test stage..'
//                 unstash 'app' 
//                 sh 'make check'
            }
            post {
                always {
                    junit '**/target/*.xml'
                }
            }
        }
        stage('Test on Windows') {
            agent {
                label 'windows'
            }
            steps {
                echo'test stage..'
//                 unstash 'app'
//                 bat 'make check' 
            }
            post {
                always {
                    junit '**/target/*.xml'
                }
            }
        }
    }
}
