pipeline {
    agent any
    parameters {
        string (name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'i am testing this')
        text (name: 'BIOGRAPHY', defaultValue:'', description:'Enter some information here.')
        booleanParam (name:'TOGGLE', defaultValue: true, description: 'Toggle value')
        choice (name: 'CHOICE', choices:['One', 'Two', 'Three'], description: 'Select one:')
        password (name: 'PASSWORD', defaultValue: 'SECRET', description: 'Enter password')
    }
    stages {
        stage ('Get Details') {
            steps {
                // env exposes environment variables, e.g. env.PATH or env.BUILD_ID
                ///////////////////////////////////////////////////////////////////
                
                echo "Build ID: ${env.BUILD_ID}"
                echo "Build URL: ${env.BUILD_URL}"
                echo "Jenkins URL: ${env.JENKINS_URL}"
                echo "Job Name: ${env.JOB_NAME}"
                
                // params exposts all parameters defined for the Pipeline as a read-only Map, e.g.:
                // params.MY_PARAM_NAME or params.PERSON
                
                echo "Hello ${params.PERSON}"
                echo "Biography: ${params.BIOGRAPHY}"
                echo "Toggle: ${params.TOGGLE}"
                echo "Choice: ${params.CHOICE}"
                echo "Password: ${params.PASSWORD}"
            }
        }
        
        stage ('Build') {
            steps {
                echo "Current Build Result: ${currentBuild.Result}"
            }
        }
        
        stage ('Deploy') {
            steps {
                echo 'Deploy...'
            }
        }
        
        stage ('Test') {
            steps {
                echo 'Test...'
            }
        }
        
        stage ('Release') {
            steps {
                echo 'Release...'
            }   
        }
        
        stage ('Abort') {
            options {
                timeout(time: 5, unit:'MINUTES')
            }
            steps {
                echo 'going to abort in 5 mins'
            }
        }
        
    }
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////

